#!/bin/sh
export SCRIPTPATH="$(dirname "$(readlink -f "$0")")"

# Down last theme
[ -f "/tmp/leftwm-theme-down" ] && /tmp/leftwm-theme-down && rm /tmp/leftwm-theme-down
ln -s "$SCRIPTPATH/down" "/tmp/leftwm-theme-down"

pgrep -x "picom" && pkill picom
nohup picom --config "$SCRIPTPATH"/picom.conf > /dev/null 2>&1 &

# wallpaper
feh --bg-fill "$SCRIPTPATH"/wallpaper.jpg

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# polybar
pkill polybar;
if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar -c "$SCRIPTPATH/polybar.config" mainbar > /dev/null &
    done
else
    polybar --reload "$SCRIPTPATH/polybar.config" mainbar > /dev/null &
fi
